const teams = {
  1: { name: "Belgium", code: "BEL", user: "name", userId: "slackId" },
  2: { name: "France", code: "FRA", user: "name", userId: "slackId" },
  3: { name: "Croatia", code: "CRO", user: "name", userId: "slackId" },
  6: { name: "Brazil", code: "BRA", user: "name", userId: "slackId" },
  7: { name: "Uruguay", code: "URU", user: "name", userId: "slackId" },
  9: { name: "Spain", code: "SPA", user: "name", userId: "slackId" },
  10: { name: "England", code: "ENG", user: "name", userId: "slackId" },
  12: { name: "Japan", code: "JAP", user: "name", userId: "slackId" },
  13: { name: "Senegal", code: "SEN", user: "name", userId: "slackId" },
  14: { name: "Serbia", code: "SER", user: "name", userId: "slackId" },
  15: { name: "Switzerland", code: "SWI", user: "name", userId: "slackId" },
  16: { name: "Mexico", code: "MEX", user: "name", userId: "slackId" },
  17: {
    name: "South Korea",
    code: "SOU",
    user: "name",
    userId: "slackId",
  },
  20: { name: "Australia", code: "AUS", user: "name", userId: "slackId" },
  21: { name: "Denmark", code: "DEN", user: "name", userId: "slackId" },
  22: { name: "Iran", code: "IRA", user: "name", userId: "slackId" },
  23: {
    name: "Saudi Arabia",
    code: "SAU",
    user: "name",
    userId: "slackId",
  },
  24: { name: "Poland", code: "POL", user: "name", userId: "slackId" },
  25: { name: "Germany", code: "GER", user: "name", userId: "slackId" },
  26: {
    name: "Argentina",
    code: "ARG",
    user: "name",
    userId: "slackId",
  },
  27: { name: "Portugal", code: "POR", user: "name", userId: "slackId" },
  28: { name: "Tunisia", code: "TUN", user: "name", userId: "slackId" },
  29: { name: "Costa Rica", code: "COS", user: "name", userId: "slackId" },
  31: { name: "Morocco", code: "MOR", user: "name", userId: "slackId" },
  767: { name: "Wales", code: "WAL", user: "name", userId: "slackId" },
  1118: {
    name: "Netherlands",
    code: "NET",
    user: "name",
    userId: "slackId",
  },
  1504: { name: "Ghana", code: "GHA", user: "name", userId: "slackId" },
  1530: { name: "Cameroon", code: "CAM", user: "name", userId: "slackId" },
  1569: { name: "Qatar", code: "QAT", user: "name", userId: "slackId" },
  2382: { name: "Ecuador", code: "ECU", user: "name", userId: "slackId" },
  2384: { name: "USA", code: "USA", user: "name", userId: "slackId" },
  5529: { name: "Canada", code: "CAN", user: "name", userId: "slackId" },
};

module.exports = teams;
